DOCKER_HUB=tranhuuphuoc22

docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_HUB}/${IMAGE_NAME}:${IMAGE_TAG}
docker tag ${IMAGE_NAME}:${IMAGE_TAG_LATEST} ${DOCKER_HUB}/${IMAGE_NAME}:${IMAGE_TAG_LATEST}

docker push ${DOCKER_HUB}/${IMAGE_NAME}:${IMAGE_TAG}
#docker push ${DOCKER_HUB}/${IMAGE_NAME}:${IMAGE_TAG_LATEST}